### ISSUE TITLE
Does not work with custom app name

### ISSUE THREAD

**Issue by pabloguerrez** [antonioribeiro/artisan-tool#1]
Hey,
helpfull package you made. Sadly, the Kernel class extends \App\Console\Kernel which is not compatible with custom app names. It should extend \Illuminate\Foundation\Console\Kernel instead. To load custom commands, just override the commands() function of the parent class.
Would be nice to implement the changes.
Greetings,
pablo

```
<?php

namespace PragmaRX\ArtisanTool\Support;

class Kernel extends \Illuminate\Foundation\Console\Kernel
{
    public function getCommands()
    {
        return $this->commands;
    }

    /**
     * Register the commands for the application.
     *
     * @return void
     */
    protected function commands()
    {
        $this->load(app_path().'/Console/Commands');

        require base_path('routes/console.php');
    }
}
```

**Comment by antonioribeiro** [comment]
No need to use Kernel anymore. Should work now.

**Comment by RicardoRamirezR** [comment]
Hi @antonioribeiro, I just install your package and got:
```
Class 'App\Console\Kernel' not found {"exception":"[object] 
(Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): 
Class 'App\\Console\\Kernel' not found at /project/vendor/pragmarx/artisan-tool/src/Support/Kernel.php:5)
```

**Comment by antonioribeiro** [comment]
Which version it installed?

**Comment by RicardoRamirezR** [comment]
I just did ```composer require pragmarx/artisan-tool```

**Comment by antonioribeiro** [comment]
Just checked the code for 0.2.1, there are zero references to Kernel in the source code

**Comment by antonioribeiro** [comment]
You can check the version doing

```
composer show | grep artisan
```

**Comment by RicardoRamirezR** [comment]
let me reinstall you package again

**Comment by RicardoRamirezR** [comment]
jeje, maybe was a github cache or something, composer just installed: ```pragmarx/artisan-tool (v0.2.1)```

**Comment by antonioribeiro** [comment]
And you still have the same problem?

**Comment by RicardoRamirezR** [comment]
no, no, its working amazing

**Comment by antonioribeiro** [comment]
Cool! Thanks for reporting anyway! It could have been a bug or something...
