### ISSUE TITLE
-c flag not working/existent on script, so commands error with "script: -c: No such file or directory"

### ISSUE THREAD

**Issue by mattstauffer** [antonioribeiro/artisan-tool#8]
On macOS, the `script` piper throws an error. I'm not familiar with script, but I ran `man script` and don't see any references to this `-c` flag that's being used to pass in the command. Help?

**Comment by mattstauffer** [comment]
Here's the line that generates the piper:

https://github.com/antonioribeiro/artisan-tool/blob/b1e247fd55ff7566d4c9389cffd0dd90de0690fd/src/Support/Executor.php#L26

Here's what that outputs for my test app:

```
script -q /Users/mattstauffer/Sites/adopt-a-drain/storage/app/console.tty -c "php /Users/mattstauffer/Sites/adopt-a-drain/artisan geolocate:postupload"
```

When I run this command manually, I get the same error:

```
script: -c: No such file or directory
```

I'm assuming this has to do with different versions of `script`, perhaps?

**Comment by antonioribeiro** [comment]
Should be fixed now. This is why I love config options in my packages. You should be able to publish config and change this, if needed:

```
'piper' => 'script -q %ttyFile% %command%',
```

This is already working in my macOS, but for a different Linux flavor this command may differ.

**Comment by mattstauffer** [comment]
@antonioribeiro 👌 Thanks sir!
